config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "text_books#index"

  resources :movies, only: [:index] do
    resource :watches, only: [:create, :destroy]
  end
  resources :aws_texts, only: [:index, :show]
  resources :line_texts, only: [:index, :show]
  resources :text_books, only: [:index, :show] do
    resource :reads, only: [:create, :destroy]
  end
  resources :questions, only: [:create, :index, :show] do
    resources :answers, only: [:create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, presence: true, length: { maximum: 30000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title , presence: true
  validates :content , presence: true
end

app/models/line_text.rb
class LineText < ApplicationRecord
  validates :genre, :title, presence: true, length: { maximum: 35 }
  validates :content, length: { maximum: 30000 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user

  validates :title , presence: true
  validates :url , presence: true
  validates :genre, presence: true

  def watched_by?(user)
    watches.find_by(user_id: user.id).present?
  end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validates :title, presence: true, length: { maximum: 300 }
  validates :detail, presence: true, length: { maximum: 3000 }
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :text_book
  validates :user_id, uniqueness: {
    scope: :text_book_id,
    message: "は同じテキストに2回以上読破済はできません"
  }
end

app/models/text_book.rb
class TextBook < ApplicationRecord
  has_many :reads, dependent: :destroy
  has_many :read_users, through: :reads, source: :user
  validates :genre, :title, presence: true, length: { maximum: 35 }
  validates :content, presence: true, length: { maximum: 30000 }

  def read_by?(user)
    reads.find_by(user_id: user.id).present?
  end

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watched_movies, through: :watches, source: :movie

  has_many :reads, dependent: :destroy
  has_many :read_text_books, through: :reads, source: :text_book

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: {
    scope: :movie_id,
    message: "は同じ動画に2回以上視聴済はできません"
  }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    answer = @question.answers.create!(answer_params)
    redirect_to @question, notice: "投稿しました"
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end
end

app/controllers/line_texts_controller.rb
class LineTextsController < ApplicationController
  def index
    @line_texts = LineText.all.order(id: :asc)
  end

  def show
    @line_text = LineText.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER = 12
  def index
    if params[:genre].nil?
      @movies = Movie.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).page(params[:page]).per(PER)
    else
      @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER)
    end
    @watched_movie_ids = current_user.watches.pluck(:movie_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    question = Question.create!(question_params)
    redirect_to questions_path
  end

  def index
    @questions = Question.all.order(id: :desc)
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @question.view_count += 1
    @question.save
    @answers = @question.answers.order(id: :desc)
    @answer = Answer.new
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController

  def create
    @text_book = TextBook.find(params[:text_book_id])
    current_user.reads.create!(text_book_id: @text_book.id)
  end

  def destroy
    @text_book = TextBook.find(params[:text_book_id])
    current_user.reads.find_by(text_book_id: @text_book.id).destroy!
  end
  
end

app/controllers/text_books_controller.rb
class TextBooksController < ApplicationController

  def index
    if params[:genre].blank?
      @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
    else
      @q = TextBook.where(genre: params[:genre]).ransack(params[:q])
    end
    @text_books = @q.result.order(:id)
    @read_textbook_ids = current_user.reads.pluck(:text_book_id)
  end
  
  def show
    @text_book = TextBook.find(params[:id])
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    current_user.watches.create!(movie_id: @movie.id)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.watches.find_by(movie_id: @movie.id).destroy!
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0] if language.present?

            case language.to_s
            when 'rb'
                lang = :ruby
            when 'yml'
                lang = :yaml
            when 'css'
                lang = :css
            when 'html'
                lang = :html
            when ''
                lang = :md
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(
            filter_html: true,
            hard_wrap: true,
            link_attributes: { rel: 'nofollow', target: "_blank" }
        )
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/views/aws_texts/index.html.erb
<div id="container">
  <section id="contents">
    <div class="text-center">
      <h4>AWS講座</h4>
    </div>
    <p>注意！！！:AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>
    <table class="table table-striped">
    <thead class="aws-table-head text-white">
        <tr class="table-primary">
          <th class="w-1" style="background-color:#5D99FF;">No.</th>
          <th class="w-5" style="background-color:#5D99FF;">内容</th>
        </tr>
      </thead>
      <tbody>
        <% @aws_texts.each.with_index(1) do |aws_text, index| %>
          <tr>
            <td><%= index %></td>
            <td><%= link_to aws_text.title, aws_text, target: "_blank", rel: "noopener" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/aws_texts/show.html.erb
<h2><%= markdown(@aws_text.title).html_safe %></h2>
<%= markdown(@aws_text.content).html_safe %>

app/views/line_texts/index.html.erb
<div id="container">
    <section id="contents">
        <div class="text-center">
        <h2 class="mb-4 text-success">LINE@</h2>
        </div>
        <table class="table table-striped">
        <thead class="line@-table-head text-white">
            <tr class="bg-success">
            <th class="w-1">No.</th>
            <th class="w-2">ジャンル</th>
            <th class="w-5">内容</th>
            </tr>
        </thead>
        <tbody>
            <% @line_texts.each.with_index(1) do |line_text, index| %>
            <tr>
                <td><%= index %></td>
                <td><%= line_text.genre %></td>
                <td><%= link_to line_text.title, line_text, target: "_blank", rel: "noopener" %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    </section>
</div>

app/views/line_texts/show.html.erb
<%= markdown(@line_text.content).html_safe %>

app/views/movies/_not_watched.html.erb
<%= link_to "視聴済みにする", movie_watches_path(movie), class: "btn btn-secondary", method: :post, remote: true %>
 

app/views/movies/_watched.html.erb
<%= link_to "視聴済みを解除", movie_watches_path(movie), class: "btn btn-primary", method: :delete, remote: true %>
 

app/views/movies/index.html.erb
<h1>動画一覧</h1>
<div id="container">
  <div class="row">
    <% @movies.each.with_index(@movies.offset_value + 1) do |movie, i| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="card border-dark mb-3">
          <div class="card-header p-0">
          <div id="movie-part">
            <div class="card-header embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" width="560" height="315" src=<%= movie.url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
            <div class="card-body">
            <p id = "movie-<%= movie.id %>">
              <% if @watched_movie_ids.include?(movie.id) %>
                <%= render "watched", movie: movie %>
              <% else %>
                <%= render "not_watched", movie: movie %>
              <% end %>
              <p class="card-text movie-title">
                <%= "No.#{i}: " + movie.title %>
              </p>
            </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @movies %>
</div>

app/views/questions/index.html.erb
<h1>新規投稿</h1>
<%= form_with model: @question, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title, "【質問】" %>
    <%= form.text_area :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :detail, "【詳細】" %>
    <%= form.text_area :title, class:'form-control' %>
  </div>
  <%= form.submit "送信", class:'btn btn-block btn-info' %>
<% end %>

<div id="question-container">
  <% @questions.each do |question| %>
    <%= link_to question do %>
      <div class="row question">
        <div class="col-md-7 title-container">
          <p><%= question.title %></p>
        </div>
        <div class="col-md-5 info text-right">
          <p>質問日<%= l question.created_at, format: :medium %></p>
          <p><%= question.view_count %>views</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="container" id="answer-container">
  <h3>【質問】</h3>
    <p><%= @question.title %></p>
  <h3>【詳細】</h3>
    <p><%= @question.detail %></p>

  <% @answers.each.with_index(1) do |answer, index| %>
    <h3>【回答<%= index %>】</h3>
      <p><%= answer.content %></p>
  <% end %>

  <h1>回答投稿</h1>
  <%= form_with model: [@question, @answer], local: true do |form| %>
    <div class="form-group">
      <%= form.label :content, "【回答】" %>
      <%= form.text_area :content, class:'form-control' %>
    </div>
    <%= form.submit "送信", data: {confirm: "投稿しますか?"} , class:'btn btn-block btn-info' %>
  <% end %>
</div>

app/views/reads/create.js.erb
document.getElementById('text_book-<%= @text_book.id %>').innerHTML = '<%= j render("text_books/read", text_book: @text_book) %>'

app/views/reads/destroy.js.erb
document.getElementById('text_book-<%= @text_book.id %>').innerHTML = '<%= j render("text_books/not_read", text_book: @text_book) %>'

app/views/text_books/_not_read.html.erb
<%= link_to "読破済みにする", text_book_reads_path(text_book), class: "btn btn-secondary", method: :post, remote: true %>
                

app/views/text_books/_read.html.erb
<%= link_to "読破済みを解除", text_book_reads_path(text_book), class: "btn btn-primary", method: :delete, remote: true %>

app/views/text_books/_search_box.html.erb
<div id="search-box">
  <%= search_form_for @q do |f| %>
    <%= hidden_field_tag :genre, params[:genre] %>
      <div class="d-flex">
        <div class="form-group flex-grow-1">
          <%= f.search_field :title_cont, placeholder: "教材を探す", class: "form-control" %>
        </div>
        <div>
          <%= f.submit "検索", class: "btn btn-primary ml-1" %>
        </div>
      </div>
  <% end %>
</div>

app/views/text_books/index.html.erb
<h1>テキスト教材</h1>
<!--- 検索 --->
<%= render 'search_box' %>

<!---テキスト教材一覧（ページネーションなし） --->
<div id="container">
  <div class="row">
    <% @text_books.each.with_index(1) do |textbook, i| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <%= link_to text_book_path(textbook.id) do %>
          <div class="card border-dark mb-3">
            <div class="card-header p-0">
              <div class="card-header embed-responsive embed-responsive-16by9">
                <img loading="lazy" class="img-fluid" width="560" height="187" src=<%= textbook.image %> >
              </div>
              <div class="card-body" width="560" height="187">
              <p id = "text_book-<%= textbook.id %>">
                <% if @read_textbook_ids.include?(textbook.id) %>
                  <%= render "read", text_book: textbook %>
                <% else %>
                  <%= render "not_read", text_book: textbook %>
                <% end %>
                <p class="card-text textbook-title">
                  <%= "【" + textbook.genre + "】" %><br>
                  <%= "No.#{i}: " + textbook.title %>
                </p>
              </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/text_books/show.html.erb
<div class="base-container mw-md">
  <section id="text-contents" >
    <h2><%= @text_book.title %></h2>
      <div class="markdown">
        <%= markdown(@text_book.content).html_safe %>
      </div>
  </section>
</div>

app/views/watches/create.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/watched", movie: @movie) %>'

app/views/watches/destroy.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/not_watched", movie: @movie) %>'