config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "text_books#index"

  resources :movies, only: [:index] do
    resource :watches, only: [:create, :destroy]
  end
  resources :aws_texts, only: [:index, :show]
  resources :line_texts, only: [:index, :show]
  resources :text_books, only: [:index, :show] do
    resource :reads, only: [:create, :destroy]
  end
  resources :questions, only: [:create, :index, :show] do
    resources :answers, only: [:create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, presence: true, length: { maximum: 30000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title , presence: true
  validates :content , presence: true
end

app/models/line_text.rb
class LineText < ApplicationRecord
  validates :genre, :title, presence: true, length: { maximum: 35 }
  validates :content, length: { maximum: 30000 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user

  validates :title , presence: true
  validates :url , presence: true
  validates :genre, presence: true

  def watched_by?(user)
    watches.find_by(user_id: user.id).present?
  end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validates :title, presence: true, length: { maximum: 300 }
  validates :detail, presence: true, length: { maximum: 3000 }
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :text_book
  validates :user_id, uniqueness: {
    scope: :text_book_id,
    message: "は同じテキストに2回以上読破済はできません"
  }
end

app/models/text_book.rb
class TextBook < ApplicationRecord
  has_many :reads, dependent: :destroy
  has_many :read_users, through: :reads, source: :user
  validates :genre, :title, presence: true, length: { maximum: 35 }
  validates :content, presence: true, length: { maximum: 30000 }

  def read_by?(user)
    reads.find_by(user_id: user.id).present?
  end

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :watches, dependent: :destroy
  has_many :watched_movies, through: :watches, source: :movie

  has_many :reads, dependent: :destroy
  has_many :read_text_books, through: :reads, source: :text_book

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: {
    scope: :movie_id,
    message: "は同じ動画に2回以上視聴済はできません"
  }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    answer = @question.answers.create!(answer_params)
    redirect_to @question, notice: "投稿しました"
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end
end

app/controllers/line_texts_controller.rb
class LineTextsController < ApplicationController
  def index
    @line_texts = LineText.all.order(id: :asc)
  end

  def show
    @line_text = LineText.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER = 12
  def index
    if params[:genre].nil?
      @movies = Movie.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).page(params[:page]).per(PER)
    else
      @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER)
    end
    @watched_movie_ids = current_user.watches.pluck(:movie_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    question = Question.create!(question_params)
    redirect_to questions_path
  end

  def index
    @questions = Question.all.order(id: :desc)
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @question.view_count += 1
    @question.save
    @answers = @question.answers.order(id: :desc)
    @answer = Answer.new
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController

  def create
    @text_book = TextBook.find(params[:text_book_id])
    current_user.reads.create!(text_book_id: @text_book.id)
  end

  def destroy
    @text_book = TextBook.find(params[:text_book_id])
    current_user.reads.find_by(text_book_id: @text_book.id).destroy!
  end
  
end

app/controllers/text_books_controller.rb
class TextBooksController < ApplicationController

  def index
    if params[:genre].blank?
      @q = TextBook.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
    else
      @q = TextBook.where(genre: params[:genre]).ransack(params[:q])
    end
    @text_books = @q.result.order(:id)
    @read_textbook_ids = current_user.reads.pluck(:text_book_id)
  end
  
  def show
    @text_book = TextBook.find(params[:id])
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    current_user.watches.create!(movie_id: @movie.id)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.watches.find_by(movie_id: @movie.id).destroy!
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0] if language.present?

            case language.to_s
            when 'rb'
                lang = :ruby
            when 'yml'
                lang = :yaml
            when 'css'
                lang = :css
            when 'html'
                lang = :html
            when ''
                lang = :md
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(
            filter_html: true,
            hard_wrap: true,
            link_attributes: { rel: 'nofollow', target: "_blank" }
        )
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-xl fixed-top navbar-dark <%= controller_name == 'line_texts' ? 'bg-success' : 'bg-primary' %>">
  <a class="navbar-brand" href="#">やんばるCODE</a>
  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Ruby/Rails教材", text_books_path, class: "dropdown-item" %>
          <%= link_to "動画教材", movies_path, class: "dropdown-item" %>
          <%= link_to "AWS講座", aws_texts_path, class: "dropdown-item" %>
          <%= link_to "ライブコーディング", movies_path(genre: "Live"), class: "dropdown-item" %>
          <%= link_to "質問集", questions_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          PHP
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "PHPテキスト教材", text_books_path(genre: "Php"), class: "dropdown-item" %>
          <%= link_to "PHP動画教材", movies_path(genre: "Php"), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item active">
        <%= link_to "対談", movies_path(genre: "Talk"), class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "情報発信", movies_path(genre: "Marketing"), class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "動画編集講座", movies_path(genre: "Movie"), class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "ライティング講座", movies_path(genre: "Writing"), class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "マネタイズ講座", movies_path(genre: "Money") , class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Line@", line_texts_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash' %>
    </header>
    <main>
      <div class="base-container <%= "mw-1200" if controller_name == "movies" %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>